// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkdwjnigohgfierszybn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZHdqbmlnb2hnZmllcnN6eWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTcxNTEsImV4cCI6MjA2ODk3MzE1MX0.FJE5Sjn0_4gRTcbRw8SpjpG4ZGYLssFT34SjfoMUNaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});